sudo: required
services:
  - docker

before_install:
  - docker build -t hoanlezuhlke/multi-d1-client -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hoanlezuhlke/multi-d1-client npm test -- --coverage

after_success:
  - docker build -t hoanlezuhlke/multi-d1-client ./client
  - docker build -t hoanlezuhlke/multi-d1-nginx ./nginx
  - docker build -t hoanlezuhlke/multi-d1-server ./server
  - docker build -t hoanlezuhlke/multi-d1-worker ./worker

  #Login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #Push image to docker hub
  - docker push hoanlezuhlke/multi-d1-client
  - docker push hoanlezuhlke/multi-d1-nginx
  - docker push hoanlezuhlke/multi-d1-server
  - docker push hoanlezuhlke/multi-d1-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-d1
  env: Multid1-env
  bucket_name: elasticbeanstalk-us-east-2-570317453708
  bucket_path: multi-d1
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
